const SEED_RECIPES = [
  {
    name: '番茄炒蛋',
    description: '经典家常快手菜，酸甜开胃',
    category: '家常菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '番茄', amount: 2, unit: '个' },
      { name: '鸡蛋', amount: 3, unit: '个' },
      { name: '葱', amount: 1, unit: '根' },
    ],
    steps: [
      { order: 1, desc: '番茄切块，鸡蛋打散加盐', tips: '番茄不要切太小' },
      { order: 2, desc: '热锅凉油，倒入蛋液炒至凝固', tips: '油温不要太高' },
      { order: 3, desc: '加入番茄翻炒出汁', tips: '' },
      { order: 4, desc: '加盐、糖调味，撒葱花出锅', tips: '加少量糖提升鲜味' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '番茄炒蛋的正确做法', url: 'https://www.bilibili.com/video/BV1xx411c7mD' },
    ],
  },
  {
    name: '红烧排骨',
    description: '色泽红亮，肉质酥烂',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 45,
    ingredients: [
      { name: '排骨', amount: 500, unit: '克' },
      { name: '姜', amount: 3, unit: '片' },
      { name: '蒜', amount: 3, unit: '瓣' },
      { name: '酱油', amount: 2, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '排骨焯水去血沫', tips: '冷水下锅' },
      { order: 2, desc: '热锅炒糖色，放入排骨翻炒', tips: '' },
      { order: 3, desc: '加酱油、料酒、姜蒜，加水没过排骨', tips: '' },
      { order: 4, desc: '大火烧开转小火炖30分钟', tips: '' },
      { order: 5, desc: '大火收汁即可', tips: '不要收太干' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '红烧排骨家常做法', url: 'https://www.bilibili.com/video/BV1EJ41127FS' },
    ],
  },
  {
    name: '清炒时蔬',
    description: '简单清爽的蔬菜小炒',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '青菜', amount: 1, unit: '斤' },
      { name: '蒜', amount: 3, unit: '瓣' },
    ],
    steps: [
      { order: 1, desc: '青菜洗净切段，蒜切末', tips: '' },
      { order: 2, desc: '热锅爆香蒜末', tips: '' },
      { order: 3, desc: '下青菜大火翻炒至熟', tips: '大火快炒保持脆嫩' },
      { order: 4, desc: '加盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '可乐鸡翅',
    description: '甜香入味，大人小孩都爱吃',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 30,
    ingredients: [
      { name: '鸡翅', amount: 8, unit: '个' },
      { name: '可乐', amount: 1, unit: '罐' },
      { name: '姜', amount: 3, unit: '片' },
      { name: '酱油', amount: 2, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '鸡翅划两刀，焯水去血沫', tips: '' },
      { order: 2, desc: '热锅煎鸡翅至两面金黄', tips: '' },
      { order: 3, desc: '倒入可乐，加酱油、姜片', tips: '可乐要没过鸡翅' },
      { order: 4, desc: '大火烧开转小火炖20分钟', tips: '' },
      { order: 5, desc: '大火收汁即可', tips: '' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '可乐鸡翅简单做法', url: 'https://www.bilibili.com/video/BV1Ws41127p0' },
    ],
  },
  {
    name: '紫菜蛋花汤',
    description: '清淡营养的快手汤',
    category: '汤品',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '紫菜', amount: 1, unit: '张' },
      { name: '鸡蛋', amount: 2, unit: '个' },
    ],
    steps: [
      { order: 1, desc: '紫菜撕碎泡水，鸡蛋打散', tips: '' },
      { order: 2, desc: '水烧开后放入紫菜', tips: '' },
      { order: 3, desc: '淋入蛋液，加盐调味', tips: '蛋液要慢慢淋入' },
      { order: 4, desc: '滴几滴香油出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '蒜蓉西兰花',
    description: '健康低脂，蒜香浓郁',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 12,
    ingredients: [
      { name: '西兰花', amount: 1, unit: '颗' },
      { name: '蒜', amount: 5, unit: '瓣' },
    ],
    steps: [
      { order: 1, desc: '西兰花掰小朵焯水', tips: '焯水加点盐保持翠绿' },
      { order: 2, desc: '蒜切末备用', tips: '' },
      { order: 3, desc: '热锅爆香蒜末，放入西兰花翻炒', tips: '' },
      { order: 4, desc: '加盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '蛋炒饭',
    description: '粒粒分明，简单美味',
    category: '主食',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '米饭', amount: 1, unit: '碗' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱', amount: 1, unit: '根' },
    ],
    steps: [
      { order: 1, desc: '鸡蛋打散，葱切末', tips: '' },
      { order: 2, desc: '热锅凉油，倒入蛋液炒散', tips: '' },
      { order: 3, desc: '加入米饭大火翻炒', tips: '米饭要打散' },
      { order: 4, desc: '加盐调味，撒葱花出锅', tips: '' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '蛋炒饭的秘诀', url: 'https://www.bilibili.com/video/BV1pJ411K7HZ' },
    ],
  },
  {
    name: '宫保鸡丁',
    description: '麻辣鲜香，经典川菜',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 25,
    ingredients: [
      { name: '鸡胸肉', amount: 300, unit: '克' },
      { name: '花生米', amount: 50, unit: '克' },
      { name: '干辣椒', amount: 5, unit: '个' },
      { name: '花椒', amount: 10, unit: '粒' },
    ],
    steps: [
      { order: 1, desc: '鸡胸肉切丁，加料酒、淀粉腌制', tips: '' },
      { order: 2, desc: '花生米炸熟备用', tips: '' },
      { order: 3, desc: '热锅爆香干辣椒和花椒', tips: '' },
      { order: 4, desc: '放入鸡丁翻炒至变色', tips: '' },
      { order: 5, desc: '加调料和花生米翻炒出锅', tips: '' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '宫保鸡丁正宗做法', url: 'https://www.bilibili.com/video/BV1Ws41127p0' },
    ],
  },
  {
    name: '麻婆豆腐',
    description: '麻辣鲜香，下饭神器',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 20,
    ingredients: [
      { name: '豆腐', amount: 1, unit: '块' },
      { name: '猪肉末', amount: 100, unit: '克' },
      { name: '豆瓣酱', amount: 1, unit: '勺' },
      { name: '花椒粉', amount: 1, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '豆腐切块焯水', tips: '' },
      { order: 2, desc: '热锅炒肉末至变色', tips: '' },
      { order: 3, desc: '加豆瓣酱炒出红油', tips: '' },
      { order: 4, desc: '加入豆腐和水烧开', tips: '' },
      { order: 5, desc: '勾芡，撒花椒粉出锅', tips: '' },
    ],
    tutorials: [
      { platform: 'bilibili', title: '麻婆豆腐家常做法', url: 'https://www.bilibili.com/video/BV1EJ41127FS' },
    ],
  },
  {
    name: '酸辣土豆丝',
    description: '开胃下饭，简单快手',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '土豆', amount: 2, unit: '个' },
      { name: '干辣椒', amount: 3, unit: '个' },
      { name: '醋', amount: 2, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '土豆去皮切丝，泡水去淀粉', tips: '切得越细越好' },
      { order: 2, desc: '热锅爆香干辣椒', tips: '' },
      { order: 3, desc: '放入土豆丝大火翻炒', tips: '' },
      { order: 4, desc: '加醋和盐调味出锅', tips: '醋要最后加' },
    ],
    tutorials: [
      { platform: 'xiaohongshu', title: '酸辣土豆丝小红书教程', url: 'https://www.xiaohongshu.com/explore/酸辣土豆丝' },
    ],
  },
  {
    name: '鱼香肉丝',
    description: '酸甜微辣，经典下饭菜',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 20,
    ingredients: [
      { name: '猪里脊', amount: 250, unit: '克' },
      { name: '木耳', amount: 50, unit: '克' },
      { name: '胡萝卜', amount: 1, unit: '根' },
      { name: '青椒', amount: 1, unit: '个' },
    ],
    steps: [
      { order: 1, desc: '里脊切丝，加料酒、淀粉腌制', tips: '' },
      { order: 2, desc: '木耳、胡萝卜、青椒切丝', tips: '' },
      { order: 3, desc: '调鱼香汁：醋、糖、酱油、豆瓣酱', tips: '糖醋比例1:1' },
      { order: 4, desc: '热锅炒肉丝至变色，加配菜翻炒', tips: '' },
      { order: 5, desc: '倒入鱼香汁翻炒均匀出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '回锅肉',
    description: '肥而不腻，川菜之王',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 25,
    ingredients: [
      { name: '五花肉', amount: 300, unit: '克' },
      { name: '蒜苗', amount: 3, unit: '根' },
      { name: '豆瓣酱', amount: 1, unit: '勺' },
      { name: '豆豉', amount: 1, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '五花肉整块冷水下锅煮至八成熟', tips: '筷子能插透即可' },
      { order: 2, desc: '捞出放凉切薄片', tips: '' },
      { order: 3, desc: '热锅不放油，下肉片煸出油脂', tips: '煸至边缘微卷' },
      { order: 4, desc: '加豆瓣酱、豆豉炒出红油', tips: '' },
      { order: 5, desc: '加蒜苗翻炒断生出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '青椒炒肉',
    description: '家常快手，百吃不厌',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '猪瘦肉', amount: 200, unit: '克' },
      { name: '青椒', amount: 3, unit: '个' },
      { name: '蒜', amount: 3, unit: '瓣' },
    ],
    steps: [
      { order: 1, desc: '猪肉切片，加酱油、淀粉腌制', tips: '' },
      { order: 2, desc: '青椒去籽切块', tips: '' },
      { order: 3, desc: '热锅炒肉片至变色盛出', tips: '' },
      { order: 4, desc: '爆香蒜末，下青椒翻炒', tips: '' },
      { order: 5, desc: '倒回肉片，加盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '糖醋里脊',
    description: '外酥里嫩，酸甜可口',
    category: '荤菜',
    difficulty: 'medium',
    estimatedMinutes: 30,
    ingredients: [
      { name: '猪里脊', amount: 300, unit: '克' },
      { name: '淀粉', amount: 3, unit: '勺' },
      { name: '番茄酱', amount: 2, unit: '勺' },
      { name: '醋', amount: 2, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '里脊切条，加盐、料酒腌制15分钟', tips: '' },
      { order: 2, desc: '裹淀粉，油炸至金黄捞出', tips: '复炸一次更酥脆' },
      { order: 3, desc: '调糖醋汁：番茄酱、醋、糖、水', tips: '' },
      { order: 4, desc: '锅中倒入糖醋汁烧开', tips: '' },
      { order: 5, desc: '放入里脊翻炒挂汁出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '红烧茄子',
    description: '软糯入味，超级下饭',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 20,
    ingredients: [
      { name: '茄子', amount: 2, unit: '根' },
      { name: '蒜', amount: 5, unit: '瓣' },
      { name: '酱油', amount: 2, unit: '勺' },
      { name: '糖', amount: 1, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '茄子切滚刀块，撒盐腌出水分', tips: '腌制后挤干水分' },
      { order: 2, desc: '热锅多放油，煎茄子至两面金黄', tips: '' },
      { order: 3, desc: '加蒜末、酱油、糖和少量水', tips: '' },
      { order: 4, desc: '焖煮3分钟，大火收汁出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '干煸四季豆',
    description: '干香微辣，口感脆嫩',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '四季豆', amount: 300, unit: '克' },
      { name: '猪肉末', amount: 50, unit: '克' },
      { name: '干辣椒', amount: 3, unit: '个' },
      { name: '蒜', amount: 3, unit: '瓣' },
    ],
    steps: [
      { order: 1, desc: '四季豆去筋掰段', tips: '' },
      { order: 2, desc: '热锅少油，煸四季豆至表皮起皱', tips: '一定要煸熟' },
      { order: 3, desc: '盛出，爆香肉末、蒜末、干辣椒', tips: '' },
      { order: 4, desc: '倒回四季豆，加盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '西红柿蛋汤',
    description: '酸甜开胃，营养暖胃',
    category: '汤品',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '番茄', amount: 2, unit: '个' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱', amount: 1, unit: '根' },
    ],
    steps: [
      { order: 1, desc: '番茄切块，鸡蛋打散', tips: '' },
      { order: 2, desc: '热锅炒番茄出汁', tips: '炒出沙感更好' },
      { order: 3, desc: '加水烧开，淋入蛋液', tips: '蛋液要慢慢淋' },
      { order: 4, desc: '加盐、香油，撒葱花出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '玉米排骨汤',
    description: '清甜滋补，老少皆宜',
    category: '汤品',
    difficulty: 'easy',
    estimatedMinutes: 60,
    ingredients: [
      { name: '排骨', amount: 400, unit: '克' },
      { name: '玉米', amount: 1, unit: '根' },
      { name: '胡萝卜', amount: 1, unit: '根' },
      { name: '姜', amount: 3, unit: '片' },
    ],
    steps: [
      { order: 1, desc: '排骨焯水去血沫', tips: '冷水下锅' },
      { order: 2, desc: '玉米、胡萝卜切块', tips: '' },
      { order: 3, desc: '所有食材放入锅中，加水没过', tips: '' },
      { order: 4, desc: '大火烧开转小火炖45分钟', tips: '' },
      { order: 5, desc: '加盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '地三鲜',
    description: '东北经典，浓香下饭',
    category: '素菜',
    difficulty: 'medium',
    estimatedMinutes: 20,
    ingredients: [
      { name: '茄子', amount: 1, unit: '根' },
      { name: '土豆', amount: 1, unit: '个' },
      { name: '青椒', amount: 2, unit: '个' },
      { name: '蒜', amount: 5, unit: '瓣' },
    ],
    steps: [
      { order: 1, desc: '茄子、土豆切块，青椒切片', tips: '' },
      { order: 2, desc: '土豆和茄子分别油炸至金黄', tips: '' },
      { order: 3, desc: '调汁：酱油、糖、淀粉水', tips: '' },
      { order: 4, desc: '爆香蒜末，倒入食材和酱汁翻炒', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '蒜苔炒肉',
    description: '清脆爽口，家常美味',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '蒜苔', amount: 300, unit: '克' },
      { name: '猪瘦肉', amount: 150, unit: '克' },
      { name: '姜', amount: 2, unit: '片' },
    ],
    steps: [
      { order: 1, desc: '蒜苔切段，猪肉切片腌制', tips: '' },
      { order: 2, desc: '热锅炒肉片至变色盛出', tips: '' },
      { order: 3, desc: '爆香姜片，下蒜苔翻炒', tips: '' },
      { order: 4, desc: '倒回肉片，加盐、酱油调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '红烧鸡腿',
    description: '酱香浓郁，肉嫩多汁',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 35,
    ingredients: [
      { name: '鸡腿', amount: 4, unit: '个' },
      { name: '姜', amount: 3, unit: '片' },
      { name: '八角', amount: 2, unit: '个' },
      { name: '酱油', amount: 3, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '鸡腿划两刀，焯水去血沫', tips: '' },
      { order: 2, desc: '热锅炒糖色，放入鸡腿翻炒', tips: '' },
      { order: 3, desc: '加酱油、姜片、八角，加水没过鸡腿', tips: '' },
      { order: 4, desc: '大火烧开转小火炖25分钟', tips: '' },
      { order: 5, desc: '大火收汁即可', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '虾仁滑蛋',
    description: '鲜嫩爽滑，营养丰富',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '虾仁', amount: 200, unit: '克' },
      { name: '鸡蛋', amount: 4, unit: '个' },
      { name: '葱', amount: 1, unit: '根' },
    ],
    steps: [
      { order: 1, desc: '虾仁去虾线，加料酒腌制', tips: '' },
      { order: 2, desc: '鸡蛋打散，加少许盐', tips: '' },
      { order: 3, desc: '热锅炒虾仁至变色', tips: '' },
      { order: 4, desc: '倒入蛋液，轻轻推动至半凝固', tips: '不要炒太老' },
      { order: 5, desc: '撒葱花出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '醋溜白菜',
    description: '酸爽脆嫩，开胃解腻',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '大白菜', amount: 1, unit: '颗' },
      { name: '干辣椒', amount: 3, unit: '个' },
      { name: '醋', amount: 2, unit: '勺' },
      { name: '花椒', amount: 5, unit: '粒' },
    ],
    steps: [
      { order: 1, desc: '白菜叶和帮分开，切块', tips: '' },
      { order: 2, desc: '热锅爆香花椒、干辣椒', tips: '' },
      { order: 3, desc: '先下白菜帮翻炒，再下叶', tips: '' },
      { order: 4, desc: '加醋和盐，大火翻炒出锅', tips: '醋要沿锅边淋入' },
    ],
    tutorials: [],
  },
  {
    name: '肉末蒸蛋',
    description: '嫩滑如豆腐，入口即化',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 20,
    ingredients: [
      { name: '鸡蛋', amount: 3, unit: '个' },
      { name: '猪肉末', amount: 100, unit: '克' },
      { name: '葱', amount: 1, unit: '根' },
    ],
    steps: [
      { order: 1, desc: '鸡蛋打散，加1.5倍温水搅匀', tips: '过筛更嫩滑' },
      { order: 2, desc: '盖保鲜膜，大火蒸10分钟', tips: '' },
      { order: 3, desc: '热锅炒肉末，加酱油调味', tips: '' },
      { order: 4, desc: '肉末浇在蒸蛋上，撒葱花', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '手撕包菜',
    description: '焦香微辣，简单快手',
    category: '素菜',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '包菜', amount: 1, unit: '颗' },
      { name: '干辣椒', amount: 3, unit: '个' },
      { name: '蒜', amount: 3, unit: '瓣' },
      { name: '醋', amount: 1, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '包菜手撕成块，蒜切末', tips: '' },
      { order: 2, desc: '热锅爆香蒜末和干辣椒', tips: '' },
      { order: 3, desc: '下包菜大火翻炒至边缘焦黄', tips: '' },
      { order: 4, desc: '加醋和盐调味出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '酸菜鱼',
    description: '酸辣开胃，鱼肉鲜嫩',
    category: '荤菜',
    difficulty: 'hard',
    estimatedMinutes: 40,
    ingredients: [
      { name: '草鱼', amount: 1, unit: '条' },
      { name: '酸菜', amount: 1, unit: '包' },
      { name: '泡椒', amount: 5, unit: '个' },
      { name: '花椒', amount: 10, unit: '粒' },
    ],
    steps: [
      { order: 1, desc: '鱼片用蛋清、淀粉腌制', tips: '鱼片要顺着纹路切' },
      { order: 2, desc: '热锅炒酸菜和泡椒出香', tips: '' },
      { order: 3, desc: '加水烧开，放入鱼骨煮5分钟', tips: '' },
      { order: 4, desc: '下鱼片，轻轻拨散，煮至变色', tips: '不要搅动' },
      { order: 5, desc: '撒花椒，浇热油激香出锅', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '葱油拌面',
    description: '葱香四溢，简单一餐',
    category: '主食',
    difficulty: 'easy',
    estimatedMinutes: 15,
    ingredients: [
      { name: '面条', amount: 200, unit: '克' },
      { name: '大葱', amount: 3, unit: '根' },
      { name: '酱油', amount: 2, unit: '勺' },
      { name: '糖', amount: 1, unit: '勺' },
    ],
    steps: [
      { order: 1, desc: '面条煮熟捞出过凉水', tips: '' },
      { order: 2, desc: '大葱切段，小火慢炸至焦黄', tips: '火不要大' },
      { order: 3, desc: '葱油浇在面上，加酱油和糖', tips: '' },
      { order: 4, desc: '拌匀即可享用', tips: '' },
    ],
    tutorials: [],
  },
  {
    name: '韭菜炒鸡蛋',
    description: '鲜香扑鼻，快手家常',
    category: '荤菜',
    difficulty: 'easy',
    estimatedMinutes: 10,
    ingredients: [
      { name: '韭菜', amount: 200, unit: '克' },
      { name: '鸡蛋', amount: 3, unit: '个' },
    ],
    steps: [
      { order: 1, desc: '韭菜切段，鸡蛋打散', tips: '' },
      { order: 2, desc: '热锅炒鸡蛋至凝固盛出', tips: '' },
      { order: 3, desc: '下韭菜大火快炒', tips: '韭菜不要炒太久' },
      { order: 4, desc: '倒回鸡蛋，加盐翻炒出锅', tips: '' },
    ],
    tutorials: [],
  },
];

async function seedRecipes(familyId, openid) {
  const result = await wx.cloud.callFunction({
    name: 'seedRecipes',
    data: { recipes: SEED_RECIPES },
  });
  if (result.result && result.result.error) {
    throw new Error(result.result.error);
  }
}

module.exports = { SEED_RECIPES, seedRecipes };
